config/routes.rb
Formulate::Application.routes.draw do
  resources :avatars

  resources :choices

  resources :forms do
    resources :fields
    get 'addtext'
    get 'addtextnumeric'
    get 'addtextarea'  
    delete 'remfield'
    post 'getfield'
    post 'update_field'
  end
  
  resources :fields

  resources :plans

  resources :accounts

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users do
     get 'logout' => "devise/sessions#destroy"
  end
  match 'home' => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
  root :to => "home#index"
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  attr_accessible :descryption
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @choices }
    end
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
    @choice = Choice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @choice }
    end
  end

  # GET /choices/new
  # GET /choices/new.json
  def new
    @choice = Choice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @choice }
    end
  end

  # GET /choices/1/edit
  def edit
    @choice = Choice.find(params[:id])
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(params[:choice])

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render json: @choice, status: :created, location: @choice }
      else
        format.html { render action: "new" }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /choices/1
  # PUT /choices/1.json
  def update
    @choice = Choice.find(params[:id])

    respond_to do |format|
      if @choice.update_attributes(params[:choice])
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice = Choice.find(params[:id])
    @choice.destroy

    respond_to do |format|
      format.html { redirect_to choices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.erb
<%= form_for(@choice) do |f| %>
  <% if @choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% @choice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descryption %><br />
    <%= f.text_field :descryption %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing choice</h1>

<%= render 'form' %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<h3>Listing choices</h3>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Descryption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @choices.each do |choice| %>
  <tr>
    <td><%= choice.descryption %></td>
    <td><%= link_to 'Show', choice %></td>
    <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
    <td><%= link_to 'Destroy', choice, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Choice', new_choice_path, :class => "btn btn-primary" %>

app/views/choices/new.html.erb
<h1>New choice</h1>

<%= render 'form' %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descryption:</b>
  <%= @choice.descryption %>
</p>


<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>