config/routes.rb
Formulate::Application.routes.draw do
  resources :avatars

  resources :choices

  resources :forms do
    resources :fields
    get 'addtext'
    get 'addtextnumeric'
    get 'addtextarea'  
    delete 'remfield'
    post 'getfield'
    post 'update_field'
  end
  
  resources :fields

  resources :plans

  resources :accounts

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users do
     get 'logout' => "devise/sessions#destroy"
  end
  match 'home' => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
  root :to => "home#index"
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :accounts
  attr_accessible :descryption, :title, :value  
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan, :html => { :class => "form-horizontal"}) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => "control-label" %>
    <div class="controls">
    	<%= f.text_field :title, :class => 'input-min' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descryption, :class => "control-label" %>
    <div class="controls">
    	<%= f.text_area :descryption, :rows => "8" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :value, :class => "control-label" %>
    <div class="controls">
    	<%= f.text_field :value %>
   	</div>
  </div>
  <div class="form-actions">
    <%= f.submit "Send", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<legend>Editing plan</legend>

<%= render 'form' %>

<%= link_to 'Show', @plan, :class => 'btn' %> |
<%= link_to 'Back', plans_path, :class => 'btn' %>

app/views/plans/index.html.erb
<legend>Listing plans</legend>
<table class='table table-hover'>
  </thead>
  <tr>
    <th>Title</th>
    <th>Descryption</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @plans.each do |plan| %>
  <tr>
    <td class='span2'><%= plan.title %></td>
    <td><%= plan.descryption %></td>
    <td><%= plan.value %></td>
    <td class='span1'><%= link_to content_tag(:i, 'Show', :class => "icon-file").html_safe, plan %></td>
    <td class='span1'><%= link_to content_tag(:i, 'Edit', :class => "icon-edit").html_safe, edit_plan_path(plan) %></td>
    <td class='span2'><%= link_to content_tag(:i, 'Delete', :class => "icon-minus-sign").html_safe, plan, confirm: 'Are you sure?', method: :delete %></td>
  </tr>  
<% end %>
  </tbody>
</table>
<div class="form-actions">
	<%= link_to 'New Plan', new_plan_path, :class => 	'btn' %>
</div>

app/views/plans/new.html.erb
<legend>New plan</legend>

<%= render 'form' %>

<%= link_to 'Back', plans_path, :class => 'btn' %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @plan.title %>
</p>

<p>
  <b>Descryption:</b>
  <%= @plan.descryption %>
</p>

<p>
  <b>Value:</b>
  <%= @plan.value %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>