config/routes.rb
Formulate::Application.routes.draw do
  resources :avatars

  resources :choices

  resources :forms do
    resources :fields
    get 'addtext'
    get 'addtextnumeric'
    get 'addtextarea'  
    delete 'remfield'
    post 'getfield'
    post 'update_field'
  end
  
  resources :fields

  resources :plans

  resources :accounts

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users do
     get 'logout' => "devise/sessions#destroy"
  end
  match 'home' => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
  root :to => "home#index"
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  belongs_to :plan
  belongs_to :avatar
  accepts_nested_attributes_for :users, :allow_destroy => true
  attr_accessible :name, :avatar_id, :plan_id, :users_attributes  
  validates_presence_of :name  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @user = User.find(params[:id])
    @account = Account.find(@user.account_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
    @avatars = Avatar.all
    @plans = Plan.all
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])    

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def verify_selected(a)
    if a.id == @account.avatar_id
      'red-border cian'
    else
      'cian'
    end
  end
end

app/views/accounts/_form.html.erb
<%= form_for(@account, :html => { :class => "form-horizontal"}) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
  	<%= f.label :name, :class => "control" %>
  	<div class="control">
    	<%= f.text_field :name %>    
    <div class="cian radius">http://<span id="span_name"><%= @account.name %></span>.formulate.com</div>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :avatar_id %>Clique on image to change 
    <div class="control form-actions yellow radius">
    	<div class="row">
    	<%= f.hidden_field :avatar_id %>
    	<%
    	@avatars.each do |a| %>
    		<div class="span1 <%= verify_selected(a) %>" id="avatar_<%= a.id %>" onclick="javascript:select_avatar(<%= a.id %>);" data-remote=true>
	    		<div class="thumbnail">
	    			<%= image_tag a.image.url %>	    			
	    		</div>
	    	</div>
    	<%
    	end    
    	%>
    	</div>
    </div>
  </div>
  <br />
  <div class="control-group">
    <%= f.label :plan_id %>
    <div class="control">
    	<%= f.collection_select :plan_id, @plans, :id, :title, :prompt => true %>
    </div>	    
  </div>
  <div class="form-actions">
    <%= f.submit "Send", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<legend>Editing account</legend>

<%= render 'form' %>
<div class="form-actions">
	<%= link_to 'Show', @account, :class => 'btn' %> 
	<%= link_to 'Back', accounts_path, :class => "btn" %>
</div>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Avatar</th>
    <th>Plan</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= account.avatar_id %></td>
    <td><%= account.plan_id %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<div id="main" class="dg">
	<legend>Account Manager</legend>
	<div class='row'>
		<div class='span9'>
			<div class='row'>
				<div class="span2 radius yellow yellow-border">
					<div class="radius white image center">
						<%= image_tag @account.avatar.image.url%>						
					</div>					
				</div>
				<div class="span6">
					<!-- Barra da URL do usuário -->
					<div class="radius cian">
						<div class="row">
							<div class="span4">
								<p class='domain'>http://<strong><%= @account.name %></strong>.formulate.com</p>
							</div>
							<div class='span2'>
								<a class="btn btn-domain" href="#">Change Domain</a>
							</div>
						</div>
					</div>			
					<br />
					<!-- Informações do usuário -->
					<div class="span6">
						<div class="row">
							<div class='span3'>
								<strong>User Information</strong><br />
								<br />
								<table>
									<tbody>
										<tr>
											<td>Name:</td>
											<td><%= @account.name %></td>
										</tr>
										<tr>
											<td>Email:</td>
											<td><%= @user.email %></td>
										</tr>
										<tr>
											<td>Plan:</td>
											<td><%= @account.plan.title %></td>
										</tr>
										<tr><td colspan='2'>&nbsp;</td></tr>
										<tr>
											<td colspan="2">
												<%= link_to "Change User Information", edit_account_path(@account.id), :class => 'btn'%>
											</td>
										</tr>										
									</tbody>
								</table>
								<br />
							</div>
							<div class='span3'><strong>Acount Usage</strong> <br /></div>
						</div>
					</div>				
				</div>	
			</div>
		</div>
	</div>
</div>
<%= link_to 'Edit', edit_account_path(@account) %> |